<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See https://github.com/magento/magento2/blob/2.1.8/COPYING.txt for license details.
 */

/**
 * @var $block \Magento\OfflinePayments\Block\Info\Checkmo
 */
/**
 * when creating a pdf from a frontend context, the admin pdf template is not found
 * use the copy provided by this extension here instead
 */
?>
<?= $block->escapeHtml($block->getMethod()->getTitle()) ?>
    {{pdf_row_separator}}
<?php if ($block->getInfo()->getAdditionalInformation()): ?>
    {{pdf_row_separator}}
    <?php if ($block->getPayableTo()): ?>
        <?= $block->escapeHtml(__('Make Check payable to: %1', $block->getPayableTo())) ?>
        {{pdf_row_separator}}
    <?php endif; ?>
    <?php if ($block->getMailingAddress()): ?>
        <?= $block->escapeHtml(__('Send Check to:')) ?>
        {{pdf_row_separator}}
        <?= /* @noEscape */ nl2br($block->escapeHtml($block->getMailingAddress())) ?>
        {{pdf_row_separator}}
    <?php endif; ?>
<?php endif; ?>
