<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See https://github.com/magento/magento2/blob/2.1.8/COPYING.txt for license details.
 */
/**
 * @var $block \Magento\OfflinePayments\Block\Info\Purchaseorder
 */
/**
 * when creating a pdf from a frontend context, the admin pdf template is not found
 * use the copy provided by this extension here instead
 */
?>
<?= $block->escapeHtml(__('Purchase Order Number: %1', $block->getInfo()->getPoNumber())) ?>
    {{pdf_row_separator}}
